### PR TITLE
Refactor as a single `nn_module`.

### PR DESCRIPTION
**Pull request by dfalbel**
Related to https://github.com/mlverse/torch/issues/932

### CODE REVIEW

**Comment by vankesteren** [comment]
Thanks! Yes this does work and I remember now that I had it like this before, however the documentation does not work with this method (try `devtools::document()` and then `?torch_sem`). Docs are working well with `R6` methods and fields through newer versions of `roxygen2`.

While this is an improvement for development work as it looks much cleaner behind the screens, it's a major issue for potential users who can now no longer have nice documentation for the methods of my `nn_module`.

**Comment by dfalbel** [comment]
You are right, that's suboptimal. We can probably provide some roxygen roclets in torch to deal with that. But I wonder if something like this would be OK for your use case:

```
#' Nn module for testing
#' @param x hello
#' @param y bye
Module <- torch::nn_module(
  "hello_world",
  initialize = function(x, y) {

  },
  #' @section Methods:
  #' ## Forward
  #'
  #' - **x** a torch tensor for hello world
  #'
  forward = function(x) {
    x
  },

  #' ## Loglik
  #' This is the description for this module parameters:
  #'
  #' - **x** lalalla
  loglik = function(x) {
    x
  },
  #' ## Fit
  #' Fit a torch_sem model using the default maximum likelihood objective.
  #' This function uses the Adam optimizer to estimate the parameters of a torch_sem
  #' - **dat** dataset (centered!) as a `torch_tensor`
  #' - **lrate** learning rate of the Adam optimizer.
  #' - **maxit** maximum number of epochs to train the model
  #' - **verbose** whether to print progress to the console
  #' - **tol** parameter change tolerance for stopping training
  fit = function() {

  },
  active = list(
    hello = function() {
      "world"
    }
  )
)
```

This renders to something like:

image

We can improve over this in the future, but in the meantime, I think it's better to hack how the docs are generated than using torch internal functions for that.

**Comment by vankesteren** [comment]
I agree and this looks good to me! will look at this soon, once I have time.

**Comment by vankesteren** [comment]
These edits were included in #11, thank you for your contribution!

**Pull request closed without merging**
